### PR TITLE
Flexible link with relative path

### PR DESCRIPTION
**Pull request by n2i**
I would like to make links which is from inside-pages, point back to `/` (root) instead of `{{ site.url }}`. I mean replace `{{ site.url }}` by relative pathes.

It's useful when launch `jekyll serve` and run site in `localhost` for testing, `site.url` update is not required.

Except for the `meta.html` file.

---
This change is [Reviewable](https://reviewable.io/reviews/taylantatli/moon/52)

### CODE REVIEW

**Comment by groggemans** [comment]
You should update this to use `site.baseurl`.  Otherwise it will mess with your urls if u use this theme at `http://domain.com/blog` for example.

**Comment by n2i** [comment]
@groggemans I got it. But this small tweak helps the site running in the dev mode (`jekyll serve`) more smoothly.

When the `site.url` is being used, generated links in site point to your `site.url` instead of the root (`/`) of the site. It's a bit awful.

**Comment by groggemans** [comment]
Let me add an example to make things more clear;

Current: `{{ site.url}}/relative/page` -> `http://domain.com/relative/page`
Dev friendly: `/relative/page` -> `/relative/page`

When the theme is used in a different root location, you currently set `site.url` to `http://domain.com/root`. This is no longer possible with the dev friendly urls you propose.

The correct solution is to use the following urls;
`{{ site.url }}{{ site.baseurl }}/relative/page` -> `http://domain.com/root/relative/page`
`{{ site.baseurl }}/relative/page` => `/root/relative/page`

This also allows you to mix dev friendly urls with urls that should always point to the online version, and keep different root locations working for both.

**Comment by n2i** [comment]
@groggemans I got it. I misunderstood something. Thank you! It seems that I have to revert those commits now, and get a little fun with sed, again.

**Comment by groggemans** [comment]
You're welcome!

**Pull request closed without merging**
