### PR TITLE
add bg-repeat = norepeat and bg-size = cover

### PR DESCRIPTION
**Pull request by loucal**
Fix background for smaller background images so it does not tile.

### CODE REVIEW

**Comment by TaylanTatli** [comment]
I won't merge this, sorry. Because if i merge this PR, this time people won't be able to use tile patterns. It's like when you fix something, you broke other things. So people can add this according to their personal usages. Thank you.

**Comment by loucal** [comment]
That's up to you just keep in mind that your repo uses a very large background image not a tile pattern so any time a user tries to customize it with a similar background image that isn't quite as large it tiles.  In my opinion when a user replaces a large bg image with a tile pattern they understand they need to make changes to the css.  Your code had me scratching my head for a few seconds because I was using it in the same use case as the repo (large bg image just "only" 1280px wide instead of your 1920px) which is why I opened the PR.  As it is now it may work for a case you are not illustrating (tile patterns) but for the situation that is displayed (a large bg image) it has a bug under 1920px.

Just something to keep in mind.

**Comment by TaylanTatli** [comment]
Here tiled pattern on my website: http://taylantatli.me/

But now with your proper explanation, it makes more sense. Yes, this will be better for background images. I will merge it now. Thank you.

BTW, i'm just curious. Are you selling this theme under sitecoxyz?

**Comment by loucal** [comment]
Thanks Taylan, I'm not selling it but I plan to use it on at least one blog.  For now sitecoxyz is just an account with a collection of soon-to-be blog sites for cheap domains I grabbed.

**Comment by loucal** [comment]
I should add I really like the style of this which is why I said "at least" one blog :)

Keep up the good work!

**Comment by TaylanTatli** [comment]
Thank you. :smile:

**Pull request merged**
